services:
  coturn:
    image: instrumentisto/coturn
    container_name: coturn
    volumes:
      - ./turn/turnserver.conf:/etc/coturn/turnserver.conf:ro
      - ./turn/certs:/etc/certs:ro
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      # - "443:443/tcp"   # TLS 쓸 때만
      - "49152-49200:49152-49200/udp"
    networks: [squadfit-net]
    restart: unless-stopped

  aiortc:
    build: ./aiortc
    container_name: aiortc
    environment:
      - AI_MODE=analyze
      - TURN_HOST=coturn # ⬅ 컨테이너끼리는 서비스명으로
      - TURN_AUTH_SECRET=devsecret # ⬅ coturn과 동일한 시크릿
    ports:
      - "7000:7000"
    depends_on:
      - coturn
    networks: [squadfit-net]
    restart: unless-stopped

networks:
  squadfit-net:
    external: true
